#ifndef __DO_RMAHDR_
#define __DO_RMAHDR_

#ifdef __cplusplus
  extern "C" {
#endif

typedef unsigned long UP;
typedef unsigned U;
typedef unsigned char UB;
typedef unsigned char scalar;
typedef struct vec32 vec32;
typedef unsigned short US;
typedef unsigned char SVAL;
typedef unsigned char TYPEB;
typedef struct qird QIRD;
typedef unsigned char UST_e;
typedef unsigned uscope_t;
typedef U  NumLibs_t;
struct vec32 {
    U  I1;
    U  I2;
};
typedef unsigned long RP;
typedef unsigned long RO;
typedef unsigned short HsimEdge;
typedef unsigned char HsimExprChar;
typedef enum {
    PD_SING = 0,
    PD_RF = 1,
    PD_PLSE = 2,
    PD_PLSE_RF = 3,
    PD_NULL = 4
} PD_e;
typedef U  FlatNodeNum;
typedef U  InstNum;
typedef unsigned long long TimeStamp64;
typedef unsigned long long TimeStamp;
typedef TimeStamp  RmaTimeStamp;
typedef TimeStamp64  RmaTimeStamp64;
typedef union {
    double I641;
    unsigned long long I642;
    unsigned  I643[2];
} rma_clock_struct;
typedef struct eblk EBLK;
typedef int (* E_fn)(void);
typedef struct eblk {
    struct eblk * I650;
    E_fn  I651;
    struct iptmpl * I652;
    unsigned I654;
    struct eblk * I655;
} eblk_struct;
typedef struct {
    RP  I650;
    RP  I651;
    RP  I652;
    unsigned I654;
    RP  I655;
} RmaEblk;
typedef union {
    double I641;
    unsigned long long I642;
    unsigned  I643[2];
} clock_struct;
typedef clock_struct  RmaClockStruct;
typedef struct RmaRetain_t RmaRetain;
struct RmaRetain_t {
    RP  I681;
    RmaEblk  I649;
    U  I682;
    US  I683 :1;
    US  I684 :4;
    US  I173 :2;
    US  state :2;
    US  I686 :1;
    US  I687 :2;
    US  I688 :2;
    US  fHsim :1;
    US  I689 :1;
    scalar  newval;
    scalar  I691;
    RP  I692;
};
typedef struct MPSched MPS;
typedef struct RmaMPSched RmaMps;
struct MPSched {
    MPS  * I671;
    scalar  I672;
    scalar  I673;
    scalar  I674;
    scalar  fHsim :1;
    scalar  I173 :6;
    U  I676;
    EBLK  I677;
    void * I678;
    UP   I679[1];
};
struct RmaMPSched {
    RP  I671;
    scalar  I672;
    scalar  I673;
    scalar  I674;
    scalar  fHsim :1;
    scalar  I173 :6;
    U  I676;
    RmaEblk  I677;
    RP  I678;
    RP   I679[1];
};
typedef struct RmaMPSchedPulse RmaMpsp;
struct RmaMPSchedPulse {
    RP  I671;
    scalar  I672;
    scalar  I673;
    scalar  I674;
    scalar  I173;
    U  I676;
    RmaEblk  I677;
    scalar  I688;
    scalar  I696;
    scalar  I697;
    scalar  I698;
    U  I699;
    RmaClockStruct  I700;
    RmaClockStruct  I701;
    U  state;
    U  I702;
    RP  I652;
    RP  I703;
    RP  I704;
    RP   I679[1];
};
typedef struct MPItem MPI;
struct MPItem {
    U  * I706;
    void * I707;
};
typedef struct {
    RmaEblk  I649;
    RP  I708;
    scalar  I709;
    scalar  I688;
    scalar  I710;
} RmaTransEventHdr;
typedef struct RmaMPSchedPulseNewCsdf RmaMpspNewCsdf;
struct RmaMPSchedPulseNewCsdf {
    RP  I671;
    scalar  I672;
    scalar  I673;
    scalar  I674;
    scalar  fHsim :1;
    scalar  I173 :6;
    U  I676;
    RmaEblk  I677;
    scalar  I688;
    scalar  I696;
    scalar  I697;
    scalar  I698;
    U  state :4;
    U  I712 :28;
    RmaClockStruct  I700;
    RmaClockStruct  I701;
    RP  I713;
    RP  I652;
    RP  I714;
    RP   I679[1];
};
typedef struct red_t {
    U  I715;
    U  I716;
    U  I717;
} RED;
typedef struct predd {
    PD_e  I173;
    RED   I718[1];
} PREDD;
typedef unsigned long long ULL;
union rhs_value {
    vec32  I719;
    scalar  I709;
    vec32  * I688;
    double I720;
    U  I721;
};
typedef struct nbs_t {
    struct nbs_t * I722;
    struct nbs_t * I724;
    void (* I725)(struct nbs_t * I726);
    unsigned I727 :1;
    unsigned I728 :1;
    unsigned I729 :1;
    unsigned I730 :1;
    unsigned I731 :27;
    U  I732;
    void * I733;
    union rhs_value I734;
    vec32  I641;
    union {
        struct nbs_t * first;
        struct nbs_t * last;
    } I736;
} NBS;
typedef struct {
    RP  I737;
    RP  I703;
    RP  I652;
    RP  I704;
    RmaEblk  I649;
    RmaEblk  I738;
    RP  I739;
    scalar  I709;
    scalar  I688;
    char state;
    uscope_t  I740;
    U  I741;
    RP  I742;
    scalar  I696;
    scalar  I697;
    scalar  I698;
    RmaClockStruct  I700;
    RmaClockStruct  I701;
    RP  I678;
} RmaPulse;
typedef struct {
    UP  I743;
    int * I744;
} TypeData;
struct etype {
    U  I553 :8;
    U  I554 :24;
    U  I555;
    U  I556 :1;
    U  I557 :1;
    U  I558 :1;
    U  I559 :1;
    U  I560 :1;
    U  I561 :1;
    U  I562 :1;
    U  I563 :1;
    U  I564 :1;
    U  I565 :4;
    U  I566 :1;
    U  I567 :1;
    U  I568 :1;
    U  I569 :1;
    U  I570 :1;
    U  I571 :1;
    U  I572 :1;
    U  I573 :1;
    U  I574 :1;
    U  I575 :1;
    U  I576 :2;
    U  I577 :1;
    U  I578 :2;
    U  I579 :1;
    U  I580 :1;
    U  I581 :2;
    U  I582;
    TypeData  * I583;
    U  I584;
    U  I585;
    U  I586 :1;
    U  I587 :1;
    U  I588 :1;
    U  I589 :1;
    U  I590 :2;
    U  I591 :2;
    U  I592 :1;
    U  I593 :1;
    U  I594 :1;
    U  I595 :1;
    U  I596 :1;
    U  I597 :1;
    U  I598 :1;
    U  I599 :1;
    U  I600 :16;
};
typedef enum {
    QIRDModuleC = 1,
    QIRDSVPackageC = 2,
    QIRDSpiceModuleC = 3
} QIRDModuleType;
typedef struct {
    U  I748 :1;
    U  I749 :1;
    U  I750 :1;
    U  I751 :1;
    U  I752 :1;
    U  I753 :1;
    U  I754 :1;
    U  I755 :1;
    U  I756 :1;
    U  I757 :1;
    U  I758 :1;
    U  I759 :1;
    U  I760 :1;
    U  I761 :1;
    U  I762 :1;
    U  I763 :1;
    U  I764 :1;
    U  I765 :1;
    U  I766 :1;
    U  I767 :1;
    QIRDModuleType  I768 :2;
    U  I769 :1;
    U  I770 :1;
    U  I771 :1;
    U  I772 :1;
    U  I773 :1;
    U  I774 :1;
    U  I775 :1;
    U  I776 :1;
    U  I777 :1;
    U  I778 :1;
    U  I779 :1;
    U  I780 :1;
    U  I781 :1;
    U  I782 :1;
    U  I783 :1;
    U  I784 :1;
    U  I785 :1;
} BitFlags;
struct qird {
    US  I4;
    US  I5;
    U  I6;
    U  I7;
    char * I8;
    char * I9;
    U  * I10;
    char * I11;
    char * I12;
    U  I13;
    U  I14;
    struct vcd_rt * I15;
    U  I17;
    struct _vcdOffset_rt * I18;
    UP  * I20;
    U  I21;
    UP  * I22;
    U  I23;
    U  I24;
    U  I25;
    U  * I26;
    U  * I27;
    void * I28;
    void * I29;
    U  I30;
    int I31;
    UP  I32;
    U  I33;
    U  I34;
    U  I35;
    UP  I36;
    U  * I37;
    BitFlags  I38;
    U  I39;
    U  I40;
    U  I41;
    U  I42;
    U  I43;
    U  * I44;
    U  I45;
    U  * I46;
    U  I47;
    U  I48;
    U  I49;
    U  I50;
    U  I51;
    U  I52;
    U  I53;
    U  * I54;
    U  * I55;
    U  I56;
    U  I57;
    U  * I58;
    U  I59;
    U  * I60;
    U  I61;
    U  I62;
    U  I63;
    U  I64;
    U  * I65;
    U  I66;
    U  * I67;
    U  I68;
    U  I69;
    U  I70;
    U  I71;
    U  I72;
    U  I73;
    U  * I74;
    char * I75;
    U  I76;
    U  I77;
    U  I78;
    U  I79;
    U  I80;
    U  * I81;
    U  I82;
    U  I83;
    UP  * I84;
    U  I85;
    U  I86;
    UP  * I87;
    U  I88;
    U  I89;
    U  I90;
    U  I91;
    U  I92;
    U  I93;
    U  * I94;
    U  I95;
    U  I96;
    U  * I97;
    U  * I98;
    U  * I99;
    U  * I100;
    U  * I101;
    U  I102;
    U  I103;
    struct taskInfo * I104;
    U  I106;
    U  I107;
    int * I108;
    UP  * I109;
    U  * I110;
    U  I111;
    U  I112;
    U  I113;
    U  I114;
    U  I115;
    struct qrefer * I116;
    U  * I118;
    unsigned * I119;
    void * I120;
    U  I121;
    U  I122;
    U  I123;
    U  I124;
    U  * I125;
    U  I126;
    U  * I127;
    U  I128;
    U  I129;
    U  I130;
    U  * I131;
    U  I132;
    U  * I133;
    U  I134;
    U  I135;
    U  * I136;
    U  I137;
    U  I138;
    U  * I139;
    U  * I140;
    U  * I141;
    U  I142;
    U  I143;
    U  I144;
    U  I145;
    U  I146;
    struct qrefee * I147;
    U  * I149;
    U  I150;
    struct qdefrefee * I151;
    U  * I153;
    int (* I154)(void);
    char * I155;
    U  I156;
    U  I157;
    void * I158;
    void * I159;
    NumLibs_t  I160;
    char * I161;
    U  * I162;
    U  I163;
    U  I164;
    U  I165;
    U  I166;
    U  I167;
    U  * I168;
    U  * I169;
    int I170;
    struct clock_load * I171;
    int I186;
    struct clock_data * I187;
    int I203;
    struct clock_hiconn * I204;
    U  I208;
    int I209;
    U  I210;
    int I211;
    U  * I212;
    U  * I213;
    U  I214;
    void * I215;
    U  I216;
    U  I217;
    UP  * I218;
    void * I219;
    U  I220;
    UP  * I221;
    U  * I222;
    int (* I223)(void);
    U  * I224;
    UP  * I225;
    U  * I226;
    U  I227 :1;
    U  I228 :31;
    U  I229;
    U  I230;
    UP  * I231;
    U  * I232;
    U  I233 :1;
    U  I234 :1;
    U  I235 :1;
    U  I236 :1;
    U  I237 :28;
    U  I238;
    U  I239;
    U  I240;
    U  I241;
    UP  * I242;
    UP  * I243;
    U  * I244;
    U  * I245;
    U  * I246;
    UP  * I247;
    UP  * I248;
    UP  * I249;
    U  * I250;
    UP  * I251;
    UP  * I252;
    UP  * I253;
    char * I254;
    U  I255;
    U  I256;
    U  I257;
    UP  * I258;
    UP  * I259;
    UP  * I260;
    UP  * I261;
    UP  * I262;
    UP  * I263;
    UP  * I264;
    UP  * I265;
    UP  * I266;
    UP  * I267;
    UP  * I268;
    UP  * I269;
    U  I270;
    U  I271;
    U  I272;
    U  I273;
    U  I274;
    U  I275;
    U  I276;
    char * I277;
    U  * I278;
    U  I279;
    U  I280;
    U  I281;
    UP  * I282;
    UP  * I283;
    UP  * I284;
    UP  * I285;
    struct daidirInfo * I286;
    struct vcs_tftable * I288;
    U  I290;
    UP  * I291;
    UP  * I292;
    U  I293;
    U  I294;
    U  I295;
    UP  * I296;
    U  * I297;
    struct qird_hil_data * I298;
    UP  (* I300)(void);
    UP  (* I301)(void);
    UP  (* I302)(void);
    UP  (* I303)(void);
    UP  (* I304)(void);
    int * I305;
    int (* I306)(void);
    char * I307;
    UP  * I308;
    UP  * I309;
    UP  (* I310)(void);
    int (* I311)(void);
    int * I312;
    int (* I313)(void);
    int * I314;
    char * I315;
    U  * I316;
    U  * I317;
    void * I318;
    U  I319;
    void * I320;
    U  I321;
    U  I322;
    U  I323;
    U  I324;
    U  I325;
    U  I326;
    UP  * I327;
    U  * I328;
    U  * I329;
    U  I330 :15;
    U  I331 :14;
    U  I332 :1;
    U  I333 :1;
    U  I334 :1;
    U  I335 :3;
    U  I336 :1;
    U  I337 :1;
    U  I338 :17;
    U  I339 :3;
    U  I340 :5;
    U  I341 :2;
    U  I342 :1;
    U  I343 :31;
    struct scope * I344;
    U  I346;
    U  I347;
    U  I348;
    U  * I349;
    U  * I350;
    U  * I351;
    U  I352;
    U  I353;
    U  I354;
    struct pcbt * I355;
    U  I365;
    U  I366;
    U  I367;
    U  I368;
    void * I369;
    void * I370;
    void * I371;
    int I372;
    U  * I373;
    U  I374;
    U  I375;
    U  I376;
    U  I377;
    U  I378;
    U  I379;
    U  I380;
    void * I381;
    UP  * I382;
    U  I383;
    U  I384;
    void * I385;
    U  I386;
    void * I387;
    U  I388;
    void * I389;
    U  I390;
    int (* I391)(void);
    int (* I392)(void);
    void * I393;
    void * I394;
    void * I395;
    U  I396;
    U  I397;
    U  I398;
    U  I399;
    U  I400;
    U  I401;
    char * I402;
    U  I403;
    U  * I404;
    U  I405;
    U  * I406;
    U  I407;
    U  I408;
    U  I409;
    U  I410;
    U  I411;
    U  I412;
    U  * I413;
    U  I414;
    U  I415;
    U  * I416;
    U  I417;
    U  I418;
    U  * I419;
    char * I420;
    U  I421;
    U  I422;
    U  I423;
    U  I424;
    U  * I425;
    U  * I426;
    U  I427;
    U  * I428;
    U  * I429;
    U  I430;
    U  I431;
    U  I432;
    U  I433;
    struct cosim_info * I434;
    U  I436;
    U  * I437;
    U  I438;
    U  I439;
    U  * I440;
    U  I441;
    U  * I442;
    U  I443;
    U  I444;
    U  * I445;
    U  I446;
    U  * I447;
    U  I448;
    U  * I449;
    U  I450;
    U  I451;
    U  I452;
    U  I453;
    U  I454;
    U  I455;
    U  I456;
    U  I457;
    U  I458;
    U  * I459;
    U  * I460;
    void (* I461)(void);
    U  * I462;
    UP  * I463;
    struct mhdl_outInfo * I464;
    UP  * I466;
    U  I467;
    UP  * I468;
    U  I469;
    void * I470;
    U  * I471;
    void * I472;
    U  I473;
    U  I474;
    void * I475;
    void * I476;
    U  * I477;
    U  * I478;
    U  * I479;
    U  * I480;
    void * I481;
    U  I482;
    void * I483;
    U  * I484;
    char * I485;
    int (* I486)(void);
    U  * I487;
    char * I488;
    char * I489;
    U  I490;
    U  * I491;
    char * I492;
    U  I493;
    struct regInitInfo * I494;
    UP  * I496;
    U  * I497;
    char * I498;
    U  I499;
    U  I500;
    U  I501;
    U  I502;
    U  I503;
    U  I504;
    U  I505;
    U  I506;
    U  * I507;
    U  * I508;
    U  I509;
    U  I510;
    U  I511;
    U  I512;
    UP  * I513;
    U  I514;
    UP  * I515;
    U  I516;
    U  I517;
    U  I518;
    U  * I519;
    U  I520;
    U  I521;
    U  I522;
    U  * I523;
    U  * I524;
    UP  * I525;
    UP  * I526;
    void * I527;
    UP  I528;
    void * I529;
    void * I530;
    void * I531;
    void * I532;
    U  * I533;
    U  * I534;
    void * I535;
    U  I536 :1;
    U  I537 :31;
    U  I538;
    U  I539;
    int I540;
    void * I541;
    UP  * I542;
    UP  I543;
    U  I544;
    char * I545;
    U  * I546;
    U  * I547;
    char * I548;
    int * I549;
    UP  * I550;
    struct etype * I551;
    U  I601;
    U  I602;
    U  * I603;
    U  I604;
    U  * I605;
    U  I606;
    U  I607;
    U  * I608;
};
typedef struct pcbt {
    U  * I357;
    UP  I358;
    U  I359;
    U  I360;
    U  I361;
    U  I362;
    U  I363;
    U  I364;
} PCBT;
struct iptmpl {
    QIRD  * I656;
    struct vcs_globals_t * I657;
    void * I659;
    UP  I660;
    UP  I661;
    struct iptmpl * I652[2];
};
typedef unsigned long long FileOffset;
typedef struct _hsimPeriodL {
    char  I824[256];
    struct _hsimPeriodL * I790;
} HsimPeriodL;
typedef struct {
    U   I826[2];
    U  I827 :1;
    U  I828 :1;
    U  I829 :8;
    U  I830 :8;
    U  I831 :8;
    U  I832 :4;
    unsigned long long I833;
    unsigned long long I834;
    unsigned long long I835;
    unsigned long long I836;
    unsigned long long I837;
    U  I838;
    U  I839;
    U  I840;
    U  I841;
    HsimPeriodL  * I842;
    HsimPeriodL  * I843;
    U  I844;
} HsimSignalMonitor;
typedef struct {
    FlatNodeNum  I845;
    InstNum  I846;
    U  I798;
    scalar  I847;
    UB  I848;
    UB  I849;
    UB  I850;
    U  I851;
    U  I852;
    U  I853;
    U  I854;
    U  I855;
    HsimSignalMonitor  * I856;
    RmaTimeStamp64  I857;
    U  I858;
    RmaTimeStamp64  I859;
} HsimNodeRecord;
typedef struct {
    RP  I860;
    RP  I652;
} RmaIbfIp;
typedef struct {
    RP  I860;
    RP  pcode;
} RmaIbfPcode;
typedef struct {
    RmaEblk  I649;
} RmaEvTriggeredOrSyncLoadCg;
typedef struct {
    RmaEblk  I649;
    RP  I861;
} RmaAnySchedSampleSCg;
typedef struct {
    RmaEblk  I649;
    RP  I862;
    RP  I861;
    vec32  I863;
} RmaAnySchedVCg;
typedef struct {
    RmaEblk  I649;
    RP  I862;
    RP  I861;
    vec32   I687[1];
} RmaAnySchedWCg;
typedef struct {
    RmaEblk  I649;
    RP  I862;
    RP  I861;
    scalar   I864[1];
} RmaAnySchedECg;
typedef struct {
    RP  I865;
} RmaRootCbkCg;
typedef struct {
    RP  I866;
} RmaRootVcdCg;
typedef struct {
    RP  I867;
} RmaRootForceCbkCg;
typedef struct {
    RmaEblk  I649;
    RP  I868;
} RmaForceCbkJmpCg;
typedef struct {
    U  I5;
    U  I645 :30;
    U  I869 :1;
    U  I870 :1;
    vec32  I719;
    U  I871;
    RP  I872;
    RP  I873;
} RmaForceSelectorV;
typedef struct {
    U  I5;
    RmaIbfPcode  I879;
} RmaNetTypeDriverGate;
typedef struct {
    U  I5;
    U  I612;
    RmaIbfPcode   I879[1];
} RmaNetTypeScatterGate;
typedef struct {
    U  I5;
    RmaIbfPcode  I879;
} RmaNetTypeGatherGate;
typedef struct {
    RmaIbfPcode  I880;
    U  I881 :3;
    U  I882 :1;
    U  I883 :1;
} RmaNbaGateOfn;
typedef struct {
    NBS  I884;
    RmaIbfPcode  I880;
} RmaNbaGate1;
typedef struct {
    RP  ptable;
    RP  pfn;
    RP  pcode;
} Rma1InputGateFaninCgS;
typedef struct {
    U  I5;
    U  iinput;
    RP  I887;
} RmaCondOptLoad;
typedef struct {
    U  I5;
    U  iinput;
    RP  I887;
} RmaMacroStateUpdate;
typedef struct {
    U  I5;
    U  state;
    U  I888;
    U  * I889;
} RmaMacroState;
typedef struct {
    U  iinput;
    RP  I890;
} RmaMultiInputLogicGateCg;
typedef struct {
    U  iinput;
    RP  ptable;
    RP  I890;
} RmaSeqPrimEdgeInputCg;
typedef struct {
    RmaEblk  I649;
    RP  pcode;
} RmaSched0GateCg;
typedef struct {
    RmaEblk  I649;
    RP  pcode;
    RP  pfn;
} RmaUdpDeltaGateCg;
typedef struct {
    RmaEblk  I649;
    RP  pcode;
    RP  pfn;
    scalar  I891;
} RmaSchedDeltaGateCg;
typedef struct {
    UB  I892;
    RP  I893;
    RP  I894;
} RmaPropNodeSeqLhsSCg;
typedef struct {
    RmaEblk  I649;
    RP  pcode;
    U  I798;
    U   I638[1];
} RmaBitEdgeEblk;
typedef struct {
    U  I5;
    RP  I718;
    RmaEblk  I649;
    RmaIbfPcode  I880;
} RmaGateDelay;
typedef struct {
    U  I5;
    union {
        RP  I1020;
        RP  I1268;
        RP  I1279;
    } I692;
    RmaIbfPcode  I880;
} RmaMPDelay;
typedef struct {
    U  I5;
    RmaPulse  I895;
    RmaIbfPcode  I880;
} RmaMPPulseHybridDelay;
typedef struct {
    U  I5;
    RmaIbfPcode  I880;
    RmaMps  I896;
} RmaMPHybridDelay;
typedef struct {
    U  I5;
    U  I897;
    RmaIbfPcode  I880;
    RmaEblk  I677;
} RmaMPHybridDelayPacked;
typedef struct {
    U  I5;
    RmaIbfPcode  I880;
    RmaMpspNewCsdf  I898;
} RmaMPPulseDelay;
typedef struct {
    U  I5;
    RmaMpsp  I898;
    RmaIbfPcode  I880;
} RmaMPPulseOptHybridDelay;
typedef struct {
    U  I5;
    U  I717;
    RmaTransEventHdr  I804;
    RP  I714;
    RmaIbfPcode  I880;
} RmaNtcTransDelay;
typedef struct {
    U  I5;
    U  I717;
    RmaEblk  I649;
    RmaIbfPcode  I880;
} RmaNtcTransMpwOptDelay;
typedef struct {
    U  I5;
    RmaEblk  I649;
    RmaIbfPcode  I880;
} RmaNtcTransZeroDelay;
typedef struct {
    U  I5;
    U  I899;
    U  I900;
    RmaTransEventHdr  I804;
    RP  I714;
    RmaIbfPcode  I880;
} RmaNtcTransDelayRF;
typedef struct {
    U  I5;
    U  I899;
    U  I900;
    RmaEblk  I649;
    RmaIbfPcode  I880;
} RmaNtcTransMpwOptDelayRF;
typedef struct {
    U  I5;
    RP  I901;
    RmaTransEventHdr  I804;
    RP  I714;
    RmaIbfPcode  I880;
} RmaICTransDelay;
typedef struct {
    U  I5;
    RP  I901;
    RmaEblk  I649;
    RmaIbfPcode  I880;
} RmaICTransMpwOptDelay;
typedef struct {
    U  I5;
    RmaEblk  I649;
    RmaIbfPcode  I880;
} RmaICTransZeroDelay;
typedef struct {
    U  I5;
    RP  I718;
    RmaEblk  I649;
    RmaIbfPcode  I880;
} RmaICSimpleDelay;
typedef struct {
    U  I5;
    union {
        RP  psimple;
        RP  I1268;
        RP  I1279;
    } I692;
    RmaIbfPcode  I880;
} RmaICDelay;
typedef struct {
    U  I5;
    RP  I718;
    RmaEblk  I649;
    RmaIbfPcode  I880;
} RmaPortDelay;
typedef struct TableAssign_ {
    struct TableAssign_ * I790;
    struct TableAssign_ * I708;
    U  I5;
    U  iinput;
    RP  ptable;
    RP  I890;
} TableAssign;
typedef struct {
    U  I5;
    RP  I708;
    RP  I903;
} RmaTableAssignList;
typedef struct {
    RP  I904;
} RmaWakeupListCg;
typedef struct {
    U  I905;
    U  I906;
    RmaTimeStamp   I907[1];
} RmaTsArray;
typedef struct {
    U  iinput;
    RP  I908;
} RmaConditionsMdb;
typedef struct {
    RP  I790;
    RP  I909;
    RP  I644;
    U  I910;
    scalar  I911;
    scalar  I912;
    US  I913 :1;
    US  I914 :1;
    US  I915 :1;
    US  I916 :1;
    US  I917 :1;
    US  I918 :1;
    US  I919 :5;
} RmaTcCoreSimple;
typedef struct {
    RP  I790;
    RP  I909;
    RP  I644;
    U  I910;
    scalar  I911;
    scalar  I912;
    US  I913 :1;
    US  I914 :1;
    US  I915 :1;
    US  I916 :1;
    US  I917 :1;
    US  I918 :1;
    US  I919 :5;
    RP  I920;
} RmaTcCoreConditional;
typedef struct {
    RP  I790;
    RP  I909;
    RP  I644;
    U  I910;
    scalar  I911;
    scalar  I912;
    US  I913 :1;
    US  I914 :1;
    US  I915 :1;
    US  I916 :1;
    US  I917 :1;
    US  I918 :1;
    US  I919 :5;
    RP  I920;
    RP  I921;
} RmaTcCoreConditionalOpt;
typedef struct {
    RP  I790;
    RP  I909;
    RP  I644;
    U  I910;
    scalar  I911;
    scalar  I912;
    US  I913 :1;
    US  I914 :1;
    US  I915 :1;
    US  I916 :1;
    US  I917 :1;
    US  I918 :1;
    US  I919 :5;
    RP  I921;
    RP  I922;
    U  I923;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtc;
typedef struct {
    RP  I909;
    RP  I644;
    U  I910;
    scalar  I911;
    scalar  I912;
    US  I913 :1;
    US  I914 :1;
    US  I915 :1;
    US  I916 :1;
    US  I917 :1;
    US  I918 :1;
    US  I919 :5;
} RmaTcCoreSimpleNoList;
typedef struct {
    RP  I909;
    RP  I644;
    U  I910;
    scalar  I911;
    scalar  I912;
    US  I913 :1;
    US  I914 :1;
    US  I915 :1;
    US  I916 :1;
    US  I917 :1;
    US  I918 :1;
    US  I919 :5;
    RP  I925;
} RmaTcCoreSimpleNoListMdb;
typedef struct {
    RP  I909;
    RP  I644;
    U  I910;
    scalar  I911;
    scalar  I912;
    US  I913 :1;
    US  I914 :1;
    US  I915 :1;
    US  I916 :1;
    US  I917 :1;
    US  I918 :1;
    US  I919 :5;
    RP  I920;
} RmaTcCoreConditionalNoList;
typedef struct {
    RP  I909;
    RP  I644;
    U  I910;
    scalar  I911;
    scalar  I912;
    US  I913 :1;
    US  I914 :1;
    US  I915 :1;
    US  I916 :1;
    US  I917 :1;
    US  I918 :1;
    US  I919 :5;
    RP  I920;
    RP  I921;
} RmaTcCoreConditionalOptNoList;
typedef struct {
    RP  I909;
    RP  I644;
    U  I910;
    scalar  I911;
    scalar  I912;
    US  I913 :1;
    US  I914 :1;
    US  I915 :1;
    US  I916 :1;
    US  I917 :1;
    US  I918 :1;
    US  I919 :5;
    RP  I921;
    RP  I922;
    U  I923;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtcNoList;
typedef struct {
    RP  I909;
    RP  I644;
    U  I910;
    scalar  I911;
    scalar  I912;
    US  I913 :1;
    US  I914 :1;
    US  I915 :1;
    US  I916 :1;
    US  I917 :1;
    US  I918 :1;
    US  I919 :5;
    RP  I921;
    RP  I922;
    RP  I925;
    U  I923;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtcNoListMdb;
typedef struct {
    RP  I909;
    RP  I644;
    U  I910;
    scalar  I911;
    scalar  I912;
    US  I913 :1;
    US  I914 :1;
    US  I915 :1;
    US  I916 :1;
    US  I917 :1;
    US  I918 :1;
    US  I919 :5;
    RP  I920;
    RP  I925;
} RmaTcCoreConditionalNoListMdb;
typedef struct {
    RP  I909;
    RP  I644;
    U  I910;
    scalar  I911;
    scalar  I912;
    US  I913 :1;
    US  I914 :1;
    US  I915 :1;
    US  I916 :1;
    US  I917 :1;
    US  I918 :1;
    US  I919 :5;
    U  I926;
    RP  I927;
    RP  I928;
    RP  I920;
    RP  I929;
    RP  I930;
    RmaTimeStamp  I931;
} RmaTcCoreNochange;
typedef struct {
    RP  I932;
    RP  I790;
} RmaTcCoreNochangeList;
typedef struct {
    RP  I908;
    RmaTimeStamp  I933;
    scalar  I934;
} RmaConditionalTSLoadNoList;
typedef struct {
    RP  I790;
    RP  I908;
    RmaTimeStamp  I933;
    scalar  I934;
} RmaConditionalTSLoad;
typedef struct {
    RmaTimeStamp  I933;
    scalar  I934;
    US  I911;
    RP  I921;
} RmaConditionalTSLoadOptNoList;
typedef struct {
    RP  I790;
    RmaTimeStamp  I933;
    scalar  I934;
    US  I911;
    RP  I921;
} RmaConditionalTSLoadOpt;
typedef struct {
    RP  I921;
    RP  I935;
    U  I923;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtcNoList;
typedef struct {
    RP  I925;
    RP  I921;
    RP  I935;
    U  I923;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtcNoListMdb;
typedef struct {
    RP  I790;
    RP  I921;
    RP  I935;
    U  I923;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtc;
typedef struct {
    U  I936;
    U  I937;
    FlatNodeNum  I938;
    U  I798;
    U  I939;
    U  I940;
    RmaIbfPcode  I880;
    union {
        scalar  I941;
        vec32  I942;
        scalar  * I943;
        vec32  * I944;
    } val;
} RmaScanSwitchData;
typedef struct {
    RP  I790;
    RP  I708;
    RP  I945;
} RmaDoublyLinkedListElem;
typedef struct {
    RP  I946;
    U  I947 :1;
    U  I948 :1;
    U  I949 :1;
    U  I950 :4;
    U  I581 :25;
    U  I951;
} RmaSwitchGateInCbkListInfo;
typedef struct {
    union {
        RmaDoublyLinkedListElem  I1309;
        RmaSwitchGateInCbkListInfo  I2;
    } I623;
    RmaIbfPcode  I880;
} RmaSwitchGate;
typedef struct RmaNonEdgeLoadData1_ {
    US  I952;
    scalar  val;
    scalar  I173 :4;
    scalar  I953 :1;
    scalar  I954 :1;
    scalar  I955 :1;
    scalar  I956 :1;
    RP  I722;
    RP  I957;
    RP  I938;
    RP  I958;
    RP  I959;
} RmaNonEdgeLoadData1;
typedef struct RmaNonEdgeLoadHdr1_ {
    UB  I960;
    UB  I961;
    RmaNonEdgeLoadData1  * I962;
    RmaNonEdgeLoadData1  * I708;
} RmaNonEdgeLoadHdr1;
typedef struct {
    U  I5;
    U  I963;
} RmaHDLCosimDUTGate;
struct clock_load {
    U  I173 :5;
    U  I174 :12;
    U  I175 :1;
    U  I176 :2;
    U  I177 :1;
    U  I178 :1;
    U  I179 :1;
    U  I180 :9;
    U  I181;
    U  I182;
    void (* pfn)(void * I184, char val);
};
typedef struct clock_data {
    U  I189 :1;
    U  I190 :1;
    U  I191 :1;
    U  I192 :1;
    U  I173 :5;
    U  I174 :12;
    U  I193 :6;
    U  I194 :1;
    U  I176 :2;
    U  I177 :1;
    U  I180 :1;
    U  I195;
    U  I196;
    U  I197;
    U  I181;
    U  I198;
    U  I199;
    U  I200;
    U  I201;
    U  I202;
} HdbsClockData;
struct clock_hiconn {
    U  I206;
    U  I207;
    U  I181;
    U  I176;
};
typedef struct _RmaDaiCg {
    RP  I964;
    RP  I965;
    U  I966;
} RmaDaiCg;
typedef union _RmaCbkMemOptUnion {
    RP  I964;
    RP  I967;
    RP  I968;
} RmaCbkMemOptUnion;
typedef struct _RmaDaiOptCg {
    RmaCbkMemOptUnion  I969;
} RmaDaiOptCg;
struct futq {
    struct futq * I662;
    struct futq * I664;
    RmaEblk  * I665;
    RmaEblk  * I666;
    U  I654;
};
struct sched_table {
    struct futq * I667;
    struct futq I668;
    struct hash_bucket * I669;
};
struct dummyq_struct {
    clock_struct  I973;
    EBLK  * I974;
    EBLK  * I975;
    struct futq * I976;
    struct futq * I977;
    struct sched_table * I978;
    struct millenium * I980;
    EBLK  * I982;
    EBLK  * I983;
    EBLK  * I984;
    EBLK  * I985;
    EBLK  * I986;
    EBLK  * I987;
    EBLK  * I988;
    EBLK  * I989;
    EBLK  * I990;
    EBLK  * I991;
    EBLK  * I992;
    EBLK  * I993;
    EBLK  * I994;
    EBLK  * I995;
    EBLK  * I996;
    EBLK  * I997;
    EBLK  * I998;
    MPS  * I999;
};
typedef void (* FP)(void *  , scalar   );
typedef void (* FP1)(void *  );
typedef void (* FPRAP)(void *  , vec32  *  , U   );
typedef U  (* FPU1)(void *  );
typedef void (* FPV)(void *  , UB  *  );
typedef void (* FPVU)(void *  , UB  *  , U   );
typedef void (* FPLSEL)(void *  , scalar   , U   );
typedef void (* FPLSELV)(void *  , vec32  *  , U   , U   );
typedef void (* FPFPV)(UB  *  , UB  *  , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPFA)(UB  *  , UB  *  , U   , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPRPV)(UB  *  , U   , U   , U   );
typedef void (* FPEVCDLSEL)(void *  , scalar   , U   , UB  *  );
typedef void (* FPEVCDLSELV)(void *  , vec32  *  , U   , U   , UB  *  );
typedef void (* FPNTYPE_L)(void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_H)(void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_LPAP)(void *  , void *  , void *  , U   , U   , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_HPAP)(void *  , void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef struct _lqueue {
    EBLK  * I650;
    EBLK  * I1000;
    int I1001;
    struct _lqueue * I681;
} Queue;
typedef struct {
    EBLK  I1003;
    U  I1004;
    union {
        void * pHeap;
        Queue  * pList;
    } I623;
    Queue   I1005[1];
} Qhdr;
extern UB   Xvalchg[];
extern UB   X4val[];
extern UB   X3val[];
extern UB   X2val[];
extern UB   XcvtstrTR[];
extern UB   Xcvtstr[];
extern UB   Xbuf[];
extern UB   Xbitnot[];
extern UB   Xwor[];
extern UB   Xwand[];
extern U   Xbitnot4val[];
extern UB   globalTable1Input[];
extern unsigned long long vcs_clocks;
extern UB   Xunion[];
extern U  fRTFrcRelCbk;
extern FP  txpFnPtr;
extern FP   rmaFunctionArray[];
extern FP   rmaFunctionRtlArray[];
extern FP   rmaFunctionLRArray[];
extern U  rmaFunctionCount;
extern U  rmaFunctionLRCount;
extern U  rmaFunctionLRDummyCount;
extern UP  rmaFunctionDummyEndPtr;
extern UB  dummyScalar;
extern UB  fScalarIsForced;
extern UB  fScalarIsReleased;
extern U  fNotimingchecks;
extern RP  * iparr;
extern FP1  * rmaPostAnySchedFnPtr;
extern FP1  * rmaPostAnySchedFnSamplePtr;
extern FP1  * rmaPostAnySchedVFnPtr;
extern FP1  * rmaPostAnySchedWFnPtr;
extern FP1  * rmaPostAnySchedEFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusNonCongruentFnPtr;
extern FP1  * rmaPostSchedUpdateEvTrigFnPtr;
extern FP1  * rmaSched0UpdateEvTrigFnPtr;
extern FP1  * rmaPostSchedRecoveryResetDbsFnPtr;
extern U  fGblDataOrTime0Prop;
extern UB   rmaEdgeStatusValArr[];
extern FP1  * propForceCbkSPostSchedCgFnPtr;
extern FP1  * propForceCbkMemoptSPostSchedCgFnPtr;
extern UB  * ptableGbl;
extern Qhdr  * lvlQueue;
extern U  mhdl_delta_count;
extern U  ignoreSchedForScanOpt;
extern U  fignoreSchedForDeadComboCloud;
extern int fZeroUser;
extern U  fEveBusPullVal;
extern U  fEveBusPullFlag;
extern UB  fNettypeIsForced;
extern UB  fNettypeIsReleased;
extern EBLK  * peblkFutQ1Head;
extern EBLK  * peblkFutQ1Tail;
extern US  * edgeActionT;
extern unsigned long long * derivedClk;
extern U  fLoopDetectMode;
extern int gFLoopDectCodeEna;
extern U  fLoopReportRT;


extern void *mempcpy(void* s1, void* s2, unsigned n);
extern UB* rmaEvalDelays(UB* pcode, scalar val);
extern UB* rmaEvalDelaysV(UB* pcode, vec32* pval);
extern void rmaPopTransEvent(UB* pcode);
extern void rmaSetupFuncArray(UP* ra, U c, U w);
extern void rmaSetupRTLoopReportPtrs(UP* funcs, UP* rtlFuncs, U cnt, U cntDummy, UP end);
extern void SinitHsimPats(void);
extern void VVrpDaicb(void* ip, U nIndex);
extern int SDaicb(void *ip, U nIndex);
extern void SDaicbForHsimNoFlagScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlagStrengthScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlag2(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimWithFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlagFrcRel(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimNoFlagFrcRel2(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void VcsHsimValueChangeCB(void* pRmaDaiCg, void* pValue, unsigned int valueFormat);
extern U isNonDesignNodeCallbackList(void* pRmaDaiCg);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void VVrpNonEventNonRegdScalarForHsimOptCbkMemopt(void* ip, U nIndex);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabFrcRel(U* mem, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimCbkMemOptNoFlagFrcRel(void* pDaiCb, unsigned char reason, int msb, int lsb, int ndx);
extern void hsimDispatchCbkMemOptForVcd(RP p, U val);
extern void* hsimGetCbkMemOptCallback(RP p);
extern void hsimDispatchCbkMemOptNoDynElabS(RP* p, U val, U isStrength);
extern void* hsimGetCbkPtrNoDynElab(RP p);
extern void hsimDispatchCbkMemOptDynElabS(U** pvcdarr, U** pcbkarr, U val, U isScalForced, U isScalReleased, U isStrength);
extern void hsimDispatchCbkMemOptNoDynElabVector(RP* /*RmaDaiOptCg* */p, void* pval, U /*RmaValueType*/ vt, U cbits);
extern void copyAndPropRootCbkCgS(RmaRootCbkCg* pRootCbk, scalar val);
extern void copyAndPropRootCbkCgV(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgW(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgE(RmaRootCbkCg* rootCbk, scalar* pval);
extern void dumpRootVcdCg(RmaRootVcdCg* pRootVcd, scalar val);
extern void Wsvvar_callback_non_dynamic1(RP* ptr, int);
extern void rmaExecEvSyncList(RP plist);
extern void Wsvvar_callback_virt_intf(RP* ptr);
extern void Wsvvar_callback_hsim_var(RP* ptr);
extern void checkAndConvertVec32To2State(vec32* value, vec32* svalue, U cbits, U* pforcedBits);
extern unsigned int fGblDataOrTime0Prop;
extern void SchedSemiLerMP1(UB* pmps, U partId);
extern void SchedSemiLerMPO(UB* pmpso, U partId);
extern void rmaDummyPropagate(void);
extern RP rmaTestCg(RP pcode, U vt, UB* value);
extern void hsUpdateModpathTimeStamp(UB* pmps);
extern void doMpd32One(UB* pmps);
extern void SchedSemiLerMP(UB* ppulse, U partId);
extern EBLK *peblkFutQ1Head;
extern EBLK *peblkFutQ1Tail;
extern void scheduleuna(UB *e, U t);
extern void scheduleuna_mp(EBLK *e, unsigned t);
extern void schedule(UB *e, U t);
extern void sched_hsopt(struct dummyq_struct * pQ, EBLK *e, U t);
extern void sched_millenium(struct dummyq_struct * pQ, void *e, U thigh, U t);
extern void schedule_1(EBLK *e);
extern void sched0(UB *e);
extern void sched0Raptor(UB *e);
extern void sched0lq(UB *e);
extern void sched0lqnc(EBLK *e);
extern void sched0una(UB *e);
extern void sched0una_th(struct dummyq_struct *pq, UB *e);
extern void hsopt_sched0u_th(struct dummyq_struct *pq, UB *e);
extern void scheduleuna_mp_th(struct dummyq_struct *pq, EBLK *e, unsigned t);
extern void schedal(UB *e);
extern void sched0_th(struct dummyq_struct * pQ, EBLK *e);
extern void sched0u(UB *e);
extern void sched0u_th(struct dummyq_struct *pq, UB *e);
extern void sched0_hsim_front_th(struct dummyq_struct * pQ, UB *e);
extern void sched0_hsim_frontlq_th(struct dummyq_struct * pQ, UB *e);
extern void sched0lq_th(struct dummyq_struct * pQ, UB *e);
extern void schedal_th(struct dummyq_struct * pQ, UB *e);
extern void scheduleuna_th(struct dummyq_struct * pQ, void *e, U t);
extern void schedule_th(struct dummyq_struct * pQ, UB *e, U t);
extern void schedule_1_th(struct dummyq_struct * pQ, EBLK *peblk);
extern void SetupLER_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLer_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXP_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXPFreeVar_th(struct dummyq_struct * pQ, EBLK *e);
extern U getVcdFlags(UB *ip);
extern void VVrpNonEventNonRegdScalarForHsimOpt(void* ip, U nIndex);
extern void VVrpNonEventNonRegdScalarForHsimOpt2(void* ip, U nIndex);
extern void SchedSemiLerTBReactiveRegion(struct eblk* peblk);
extern void SchedSemiLerTBReactiveRegion_th(struct eblk* peblk, U partId);
extern void SchedSemiLerTr(UB* peblk, U partId);
extern void SchedSemiLerNBA(UB* peblk, U partId);
extern void NBA_Semiler(void *ip, void *pNBS);
extern void sched0sd_hsim(UB* peblk);
extern void appendNtcEvent(UB* phdr, scalar s, U schedDelta);
extern void schedRetainHsim(MPS* pMPS, scalar sv, scalar pv);
extern void updateRetainHsim(MPS* pMPS,scalar sv, scalar pv);
extern void hsimRegisterEdge(void* sm,  scalar s);
extern U pvcsGetPartId();
extern void HsimPVCSPartIdCheck(U instNo);
extern void debug_func(U partId, struct dummyq_struct* pQ, EBLK* EblkLastEventx); 
extern struct dummyq_struct* pvcsGetQ(U thid);
extern EBLK* pvcsGetLastEventEblk(U thid);
extern void insertTransEvent(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, int re, UB* predd, U fpdd);
extern void insertNtcEventRF(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, U* delays);
extern U doTimingViolation(RmaTimeStamp ts,RP* pdata, U fskew, U limit, U floaded, U fcondopt, RmaTimeStamp tsNochange);
extern void sched_gate_hsim(EBLK* peblk, unsigned t, RP* offset);
extern int getCurSchedRegion();
extern FP getRoutPtr(RP, U);
extern U rmaChangeCheckAndUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern void rmaUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaChangeCheckAndUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaLhsPartSelUpdateE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaUpdateWithForceSelectorE(scalar* pvalDst, scalar* pvalSrc, U cbits, U* pforceSelector);
extern void rmaUpdateWFromE(vec32* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaLhsPartSelWithChangeCheckE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaLhsPartSelWFromE(vec32* pvalDst, scalar* pvalSrc, U index,U width);
extern U rmaChangeCheckAndUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern U rmaLhsPartSelWithChangeCheckW(vec32* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern U rmaLhsPartSelWithChangeCheckEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelUpdateW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void rmaEvalWunionW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWorW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWandW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalUnionE(scalar* dst, scalar* src, U cbits, U count, RP ptable);
typedef U RmaCgFunctionType;
extern RmaIbfPcode* rmaEvalPartSelectsW(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsWToE(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsEToE(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce, UB* pevcdStatus);
extern RmaIbfPcode* rmaEvalPartSelectsEToW(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern U rmaEvalBitPosEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U VcsForceVecVCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U/*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecVCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecWCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecWCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecECg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecACg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecCg(UB* pcode, UB* pvDst, U ibeginDst, U width, U /*RmaValueType*/ type,U fisRoot, UB* prhsDst, U frhs, U* pforcedbits);
extern U VcsDriveBitsAndDoChangeCheckV(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckW(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckE(scalar* pvSel, scalar* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern void cgvecDebug_Eblk(UB* pcode);
extern U rmaCmpW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void copyVec32ArrMask(vec32* pv1, vec32* pv2, U len, U* mask);
extern void* memcpy(void*, const void*, size_t);
extern int memcmp(const void*, const void*, size_t);
extern void propagateScanOptPathVal(EBLK *peblk);
extern UB* rmaProcessScanSwitches(UB* pcode, scalar val);
extern UB* rmaProcessScanSwitchesV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanoptDump(UB* pcode, scalar val);
extern UB* rmaProcessScanoptDumpV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanChainOptSeqPrims(UB* pcode, scalar val);
extern void rmaProcessPvcsCcn(UB* pcode, scalar val);
extern void rmaProcessPvcsCcnE(UB* pcode, scalar* val);
extern void rmaProcessPvcsCcnW(UB* pcode, vec32* val);
extern void rmaProcessPvcsCcnV(UB* pcode, vec32* val);
extern void rmaProcessPvcsCcnCompiledS(UB* pcode, U offset, scalar ibnval);
extern void rmaProcessPvcsCcnCompiledV(UB* pcode, U offset, vec32* pval);
extern void schedResetRecoveryDbs(U cedges, EBLK* peblkFirst);
extern UB* rmaEvalUnaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVOneFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVLargeFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalAndOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpV(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpV(UB* pcode, vec32* value);
extern UB* rmaEvalTernaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalTernaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalBinaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpS(UB* pcode, scalar val);
extern scalar rmaGetScalarFromWCg(vec32* pval, U index);
extern void rmaSetScalarInWCg(vec32* pval, U index, scalar s);
extern void rmaCountRaptorBits(void* pval, void* pvalPrev, U cbits, U vt);
extern void setHsimFunc(void* ip);
extern void unsetHsimFunc(void* ip);
extern UB* getEvcdStatusByFlagsE(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsV(vec32* pvec32, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsS(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table);
extern UB* getSingleDrvEvcdStatusS(UB value, U fTBDriver);
extern UB* getSingleDrvEvcdStatusE(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getSingleDrvEvcdStatusV(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getEvcdStatusByDrvEvcdStatus(UB* pdrvevcdStatus, U cdrivers, UB* table, U cbits);
extern void evcdCallback(UP pcode, U cbits);
extern UB* getSavedEvcdStatus(void);
extern void saveEvcdStatus(UB*);
extern void mhdlMarkExport(void*, U);
extern void levelInsertQueue(int);
extern void VcsRciRtl(RP pcode);
extern U fLoopDetectMode;
extern int gFLoopDectCodeEna;
extern U fLoopReportRT;
extern void rtSched0LoopDectDumpProcess(void* e, void* rtn, void* PQ);
extern void pushHsimRtnCtxt(void* pcode);
extern void popHsimRtnCtxt();
extern EBLK* loopReportInlinedSched0Wrapper(EBLK *peblk);
extern void loopReportSched0Wrapper(EBLK *peblk, unsigned int sfType, unsigned int fTH, struct dummyq_struct* pq);
extern void loopReportSchedSemiLerWrapper(EBLK *peblk, int sfType);
extern void CallGraphPushNodeAndAddToGraph(UP flatNode, UP instNum, U dummy);
extern void CallGraphPopNode(void);
extern RP elabGetIpTpl(U in);
extern U rmaEvalBitBothEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQXW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval01EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval0XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval10EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval1XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX1EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX0EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitPosEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitBothEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern void rmaScheduleNbaGate(RP pcode, scalar val);
extern void rmaEvaluateDynamicGateLoadsCg(RP p, scalar s);
extern void rmaEvaluateFusedWithDynamicGateLoadsCg(RP p, scalar s);
extern void rmaScheduleGatedClockEdgeLoad(UB* p, US* ea, U fNonEdgeLoad, UB* plist, scalar v);
extern void rmaRemoveNonEdgeLoads(UB* pcode);
extern void handlePCBs(UB* p, U i);
extern void markMasterClkOvaLists(U fdbs, RP p);
extern void HDLCosimProcessDUTInputChange(U inputId, void* val);
extern U rmaIsS2State(scalar s);
extern U rmaIsV2State(vec32* pval, U cbits);
extern U rmaIsW2State(vec32* pval, U cbits);
extern U rmaIsE2State(scalar* pval, U cbits);
extern void rmaUpdateRecordFor2State(HsimNodeRecord* record, U f2state);
typedef void (*FuncPtr)();
static inline U asm_bsf (U in)
{
#if defined(linux)
    U out;
    asm ("movl %1, %%eax; bsf %%eax, %%eax; movl %%eax, %0;"
        :"=r"(out)
        :"r"(in)
        :"%eax"
        );
    return out;
#else
    return 0;
#endif
}


#ifdef __cplusplus
extern "C" {
#endif
void  hsM_0_0 (UB  * pcode, scalar  val);
void  hsM_0_1 (UB  * pcode, scalar  val, U  I1026, scalar  * I1025);
void  hsM_0_2 (UB  * pcode);
void  hsM_1_0 (UB  * pcode, scalar  val);
void  hsM_1_1 (UB  * pcode, scalar  val, U  I1026, scalar  * I1025);
void  hsM_1_2 (UB  * pcode);
void  hsG_0 (struct dummyq_struct * I1012, EBLK  * I1013, U  I717);
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
  }
#endif
#endif /*__DO_RMAHDR_*/

